#!/bin/bash

# Define the path to the docker-compose file and the container id file
DOCKER_COMPOSE_FILE="./docker-compose.yaml"
CONTAINER_ID_FILE="container.id"

# Run docker-compose build
echo "Building docker images..."
sudo docker-compose -f "$DOCKER_COMPOSE_FILE" build

# Check if container.id file exists and if it does, stop and remove the container
if [ -f "$CONTAINER_ID_FILE" ]; then
    CONTAINER_ID=$(cat "$CONTAINER_ID_FILE")
    echo "Stopping and removing the container with ID: $CONTAINER_ID"
    sudo docker stop "$CONTAINER_ID" && sudo docker rm "$CONTAINER_ID"
fi

# Run docker-compose up in detached mode and get the new container ID
echo "Starting up the new container..."
NEW_CONTAINER_ID=$(sudo docker-compose -f "$DOCKER_COMPOSE_FILE" up -d sh-admin && sudo docker-compose -f "$DOCKER_COMPOSE_FILE" ps -q sh-admin)

# Check if the command to start the container was successful
if [ $? -eq 0 ]; then
    # Save the new container ID to container.id file
    echo "$NEW_CONTAINER_ID" > "$CONTAINER_ID_FILE"
    echo "Deployed successfully. New container ID: $NEW_CONTAINER_ID"
else
    echo "Failed to start the container."
    exit 1
fi
